
import v from './variables'

export default {
  na1: { margin: `-${v.spacingExtraSmall}` },
  na2: { margin: `-${v.spacingSmall}`},
  na3: { margin: `-${v.spacingMedium}` },
  na4: { margin: `-${v.spacingLarge}` },
  na5: { margin: `-${v.spacingExtraLarge}` },
  na6: { margin: `-${v.spacingExtraExtraLarge}` },
  na7: { margin: `-${v.spacingExtraExtraExtraLarge}` },
  nl1: { marginLeft: `-${v.spacingExtraSmall}` },
  nl2: { marginLeft: `-${v.spacingSmall}` },
  nl3: { marginLeft: `-${v.spacingMedium}` },
  nl4: { marginLeft: `-${v.spacingLarge}` },
  nl5: { marginLeft: `-${v.spacingExtraLarge}` },
  nl6: { marginLeft: `-${v.spacingExtraExtraLarge}` },
  nl7: { marginLeft: `-${v.spacingExtraExtraExtraLarge}` },
  nr1: { marginRight: `-${v.spacingExtraSmall}` },
  nr2: { marginRight: `-${v.spacingSmall}` },
  nr3: { marginRight: `-${v.spacingMedium}` },
  nr4: { marginRight: `-${v.spacingLarge}` },
  nr5: { marginRight: `-${v.spacingExtraLarge}` },
  nr6: { marginRight: `-${v.spacingExtraExtraLarge}` },
  nr7: { marginRight: `-${v.spacingExtraExtraExtraLarge}` },
  nb1: { marginBottom: `-${v.spacingExtraSmall}` },
  nb2: { marginBottom: `-${v.spacingSmall}` },
  nb3: { marginBottom: `-${v.spacingMedium}` },
  nb4: { marginBottom: `-${v.spacingLarge}` },
  nb5: { marginBottom: `-${v.spacingExtraLarge}` },
  nb6: { marginBottom: `-${v.spacingExtraExtraLarge}` },
  nb7: { marginBottom: `-${v.spacingExtraExtraExtraLarge}` },
  nt1: { marginTop: `-${v.spacingExtraSmall}` },
  nt2: { marginTop: `-${v.spacingSmall}` },
  nt3: { marginTop: `-${v.spacingMedium}` },
  nt4: { marginTop: `-${v.spacingLarge}` },
  nt5: { marginTop: `-${v.spacingExtraLarge}` },
  nt6: { marginTop: `-${v.spacingExtraExtraLarge}` },
  nt7: { marginTop: `-${v.spacingExtraExtraExtraLarge}` }
}
