export default {
    'sansSerif': `-apple-system, BlinkMacSystemFont, 'avenir next', avenir, helvetica, 'helvetica neue', ubuntu, roboto, noto, 'segoe ui', arial, sans-serif`,
    'serif': 'georgia, serif',
    'fontSizeHeadline': '6rem',
    'fontSizeSubheadline': '5rem',
    'fontSize1': '3rem',
    'fontSize2': '2.25rem',
    'fontSize3': '1.5rem',
    'fontSize4': '1.25rem',
    'fontSize5': '1rem',
    'fontSize6': '.875rem',
    'fontSize7': '.75rem',
    'lineHeightSolid': '1',
    'lineHeightTitle': '1.25',
    'lineHeightCopy': '1.5',
    'measure': '30em',
    'measureNarrow': '20em',
    'measureWide': '34em',
    'spacingNone': '0',
    'spacingExtraSmall': '.25rem',
    'spacingSmall': '.5rem',
    'spacingMedium': '1rem',
    'spacingLarge': '2rem',
    'spacingExtraLarge': '4rem',
    'spacingExtraExtraLarge': '8rem',
    'spacingExtraExtraExtraLarge': '16rem',
    'spacingCopySeparator': '1.5em',
    'height1': '1rem',
    'height2': '2rem',
    'height3': '4rem',
    'height4': '8rem',
    'height5': '16rem',
    'width1': '1rem',
    'width2': '2rem',
    'width3': '4rem',
    'width4': '8rem',
    'width5': '16rem',
    'maxWidth1': '1rem',
    'maxWidth2': '2rem',
    'maxWidth3': '4rem',
    'maxWidth4': '8rem',
    'maxWidth5': '16rem',
    'maxWidth6': '32rem',
    'maxWidth7': '48rem',
    'maxWidth8': '64rem',
    'maxWidth9': '96rem',
    'borderRadiusNone': '0',
    'borderRadius1': '.125rem',
    'borderRadius2': '.25rem',
    'borderRadius3': '.5rem',
    'borderRadius4': '1rem',
    'borderRadiusCircle': '100%',
    'borderRadiusPill': '9999px',
    'borderWidthNone': '0',
    'borderWidth1': '.125rem',
    'borderWidth2': '.25rem',
    'borderWidth3': '.5rem',
    'borderWidth4': '1rem',
    'borderWidth5': '2rem',
    'boxShadow1': '0px 0px 4px 2px rgba( 0, 0, 0, 0.2 )',
    'boxShadow2': '0px 0px 8px 2px rgba( 0, 0, 0, 0.2 )',
    'boxShadow3': '2px 2px 4px 2px rgba( 0, 0, 0, 0.2 )',
    'boxShadow4': '2px 2px 8px 0px rgba( 0, 0, 0, 0.2 )',
    'boxShadow5': '4px 4px 8px 0px rgba( 0, 0, 0, 0.2 )'
};
